sudo: required

language: python

env:
  DOCKER_COMPOSE_VERSION: 1.24.1

os:
  - linux

branches:
  only:
    - master
    - develop

python:
  - 3.6

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install: docker-compose up -d --build

script:
  - git clone -b features/wms-monitor https://github.com/panoptes-organization/snakemake
  - cd snakemake
  - virtualenv -p `which python3` venv_snakemake_develop
  - source venv_snakemake_develop/bin/activate
  - pip install .
  - cd ..
  - git clone https://github.com/panoptes-organization/snakemake_example_workflow.git
  - cd snakemake_example_workflow
  - sed -i 's/5000/8000/g' run_local.sh
  - bash run_local.sh
  - cd ../
  - deactivate 
  - virtualenv -p `which python3` venv_test
  - source venv_test/bin/activate
  - pip install -U 'requests==2.22.0' 'pytest'
  - py.test tests/api_test.py --ignore server/
  - deactivate

after_script:
  - docker-compose down
