name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -c conda-forge -c bioconda snakemake pip mamba
        pip install .
    - name: Deploy panoptes
      run: |
        panoptes &
    - name: Test panoptes
      run: |
        response=$(curl http://127.0.0.1:5000/api/service-info)
        if [ "$response" = "{\"status\":\"running\"}" ]; then
                echo "Success";
                exit 0;
        else
                echo "Fail";
                exit 1;
        fi
    - name: Run test workflow
      run: |
        snakemake --version
        cd ..
        git clone https://github.com/panoptes-organization/snakemake_example_workflow.git
        cd snakemake_example_workflow
        ls
        bash run_local.sh
        